// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPBXqk_SLh81976QvZJjM0lOokR6uDQlw',
    appId: '1:49404641288:web:a3e53106fc18a1212d91bd',
    messagingSenderId: '49404641288',
    projectId: 'moodeatsai',
    authDomain: 'moodeatsai.firebaseapp.com',
    storageBucket: 'moodeatsai.appspot.com',
    measurementId: 'G-0WQRN92H18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLRtUBNyKrvLtbtq2JGFsdTsF0LQOagzQ',
    appId: '1:49404641288:android:cb2e4440efd0f3b92d91bd',
    messagingSenderId: '49404641288',
    projectId: 'moodeatsai',
    storageBucket: 'moodeatsai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgDMKazXOTrCS4TGd_fe4rLiOlCwIg9F0',
    appId: '1:49404641288:ios:8c7712b34f18e8052d91bd',
    messagingSenderId: '49404641288',
    projectId: 'moodeatsai',
    storageBucket: 'moodeatsai.appspot.com',
    iosBundleId: 'com.example.moodeatsai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgDMKazXOTrCS4TGd_fe4rLiOlCwIg9F0',
    appId: '1:49404641288:ios:8c7712b34f18e8052d91bd',
    messagingSenderId: '49404641288',
    projectId: 'moodeatsai',
    storageBucket: 'moodeatsai.appspot.com',
    iosBundleId: 'com.example.moodeatsai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPBXqk_SLh81976QvZJjM0lOokR6uDQlw',
    appId: '1:49404641288:web:05ce95d02cbf272f2d91bd',
    messagingSenderId: '49404641288',
    projectId: 'moodeatsai',
    authDomain: 'moodeatsai.firebaseapp.com',
    storageBucket: 'moodeatsai.appspot.com',
    measurementId: 'G-G7PRH6ZZ43',
  );
}
